apiVersion: batch/v1
kind: CronJob
metadata:
  name: my-react-cronjob
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: my-react-cronjob-container
            image: my-react-app:{{ .Values.image.tag }}
            command: ["node", "scripts/fetchData.js"] # Example cron job task
          restartPolicy: OnFailure
