apiVersion: batch/v1
kind: CronJob
metadata:
  name: my-cronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: my-container
            image: your-repo/your-image:latest
            imagePullPolicy: IfNotPresent
            command: ["java", "-jar", "/app/your-app.jar"]
          restartPolicy: OnFailure

